# @Author: Paul Druce <pauldruce>
# @Date:   2019-10-20T20:11:24+01:00
# @Email:  pjdruce@gmail.com
# @Last modified by:   pauldruce
# @Last modified time: 2020-06-23T16:02:35+01:00



# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Paul J Druce's site
portrait_url: /assets/images/Portrait_square.jpg
avatar_url: /assets/images/favicon.ico
email: pjdruce@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A place to collect my notes on the maths of physics and anything related.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.pauldruce.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: paulcannotthink
github_username:  pauldruce
orcid_id: 0000-0002-2774-964X
arxiv_id: druce_p_1
inspire: P.Druce.1

include:
  - _pages
# Google Analytics
google_analytics: UA-134367955-1
# Disqus Comments
comments: true

# Build settings
markdown: Pandoc
highlighter: rouge
pandoc:
  extensions:
    - citeproc
    - mathjax
    - toc
    - bibliography: ./assets/bibtex/website_bib.bib
    - csl: ./assets/bibtex/acm-sigchi-proceedings.csl
    - filter: '/Users/pauldruce/.local/bin/pandoc-sidenote'


plugins:
  - jekyll-feed
  - jekyll-pandoc
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-spaceship

jekyll-spaceship:
  processors:
    # - plantuml-processor
    # - mermaid-processor
    # - polyfill-processor
    - media-processor
    - emoji-processor
    # - element-processo
  plantuml-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: plantuml
    syntax:
      code: 'plantuml!'
      custom: ['@startuml', '@enduml']
    src: http://www.plantuml.com/plantuml/svg/
  mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: 'mermaid!'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
    src: https://mermaid.ink/svg/
  media-processor:
    default:
      id: 'media-{id}'
      class: 'media'
      width: '100%'
      height: 350
      frameborder: 0
      style: 'max-width: 600px; outline: none;'
      allow: 'encrypted-media; picture-in-picture'
  emoji-processor:
    css:
      class: emoji
    src: https://github.githubassets.com/images/icons/emoji/
