name: CI Checks
on: pull_request

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - uses: haskell-actions/setup@v2
        id: haskell-setup

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc \
            make

      - name: Restore cached dependencies
        uses: actions/cache/restore@v4
        id: cache
        with:
          path: ${{ steps.haskell-setup.outputs.cabal-store }}
          key: ${{ runner.os }}-cabal
          restore-keys: |
            ${{ runner.os }}-cabal-

      - name: Install Pandoc and pandoc-sidenote
        run: |
          which cabal
          cabal update
          cabal install pandoc-cli pandoc-sidenote

      # Cache dependencies already here, so that we do not have to rebuild them should the subsequent steps fail.
      - name: Save cached dependencies
        uses: actions/cache/save@v4
        # If we had an exact cache hit, trying to save the cache would error because of key clash.
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.haskell-setup.outputs.cabal-store }}
          key: ${{ runner.os }}-cabal

      - name: Build
        run: |
          which pandoc
          make production

      - name: Check if there are any changes
        run: |
          set +e
          diff_output=$(git diff HEAD --quiet)
          diff_return_value=$?
          if [ $diff_return_value -ne 0 ]; then
            echo "There are changes after building the website."
            echo "Make sure you have an up-to-date production build of the website commited"
            echo "Git diff output: "
            echo "diff_output"
            exit 1
          fi
